

DROP TABLE STSBOARD;

CREATE SEQUENCE STSBD_SEQ NOCACHE;

CREATE TABLE STSBOARD(
	BD_NO NUMBER PRIMARY KEY,
	BD_NAME VARCHAR2(100) NOT NULL,
	BD_TITLE VARCHAR2(200) NOT NULL,
	BD_CONTENT VARCHAR2(4000) NOT NULL,
	BD_DATE DATE NOT NULL
);

INSERT INTO STSBOARD VALUES(STSBD_SEQ.NEXTVAL, '개발자', '스프링 MVC 게시판', 'jsp servelt 그리고 spring', SYSDATE);

SELECT * FROM STSBOARD;

COMMIT;

DROP SEQUENCE STSMEM_SEQ;
DROP TABLE STSMEMBER;

CREATE SEQUENCE STSMEM_SEQ NOCACHE;

CREATE TABLE STSMEMBER(
    BM_NO NUMBER NOT NULL,
    BM_ID VARCHAR2(1000) NOT NULL,
    BM_PW VARCHAR2(1000) NOT NULL,
    BM_NAME VARCHAR2(1000) NOT NULL,
    BM_ADDR VARCHAR2(1000) NOT NULL,
    BM_PHONE VARCHAR2(1000) NOT NULL,
    BM_EMAIL VARCHAR2(1000) NOT NULL,
    BM_ENABLED VARCHAR2(2) NOT NULL,
    BM_ROLE VARCHAR2(50) NOT NULL,
    CONSTRAINT STSMEMBER_PK PRIMARY KEY(BM_NO),
    CONSTRAINT STSMEMBER_UQ_ID UNIQUE(BM_ID),
    CONSTRAINT STSMEMBER_UQ_PHONE UNIQUE(BM_PHONE),
    CONSTRAINT STSMEMBER_UQ_EMAIL UNIQUE(BM_EMAIL),
    CONSTRAINT STSMEMBER_ENABLED_CHK CHECK(BM_ENABLED IN('Y', 'N'))
);

INSERT INTO STSMEMBER VALUES(STSBD_SEQ.NEXTVAL, 'USER1', '1234','김철수', '서울시 종로구', '010-2224-5532', 'cskim@sts.com', 'Y', 'USER');

SELECT * FROM STSMEMBER;

commit;